{{- if not .Values.secret.existingSecret }}
{{- if .Values.secret.files }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intellitrader.fullname" . }}-secret
  labels:
    {{- include "intellitrader.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret.files }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
{{- end }}
